command: [
  "streamlit", 
  "run",
  "app.py"
]

resources:
  # Databricks-hosted foundation model
  - name: healthbot_llm
    type: foundation_model
    identifier: databricks-meta-llama-3-1-405b-instruct

  # Vector Search index
  - name: vs_index
    type: vector_search_index
    identifier: chatbot_dev.gold.patient_vector_index

env:
  - name: LLM_MODEL_NAME
    value: databricks-meta-llama-3-1-405b-instruct

  - name: VS_ENDPOINT_NAME
    value: healthbot-vs-endpoint

  - name: VS_INDEX_FULL_NAME
    value: chatbot_dev.gold.patient_vector_index
